// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLzZHoH2JSn1vEWufl0acjrkGohsBtdE',
    appId: '1:270601916854:web:fd75aafee3e1afd3a37117',
    messagingSenderId: '270601916854',
    projectId: 'fir-211de',
    authDomain: 'fir-211de.firebaseapp.com',
    databaseURL: 'https://fir-211de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-211de.firebasestorage.app',
    measurementId: 'G-C8RDL2S1BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2GQKk1n3Y6KaA0ySlIEptpuLWiMhwi8',
    appId: '1:270601916854:android:842a73a7bd855531a37117',
    messagingSenderId: '270601916854',
    projectId: 'fir-211de',
    databaseURL: 'https://fir-211de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-211de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiNWvYwsDVTIvqdelfld0eSNo7PEPhbg',
    appId: '1:270601916854:ios:8a82c314d8aae0fea37117',
    messagingSenderId: '270601916854',
    projectId: 'fir-211de',
    databaseURL: 'https://fir-211de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-211de.firebasestorage.app',
    iosBundleId: 'com.example.spacewordSkorgameplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMiNWvYwsDVTIvqdelfld0eSNo7PEPhbg',
    appId: '1:270601916854:ios:8a82c314d8aae0fea37117',
    messagingSenderId: '270601916854',
    projectId: 'fir-211de',
    databaseURL: 'https://fir-211de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-211de.firebasestorage.app',
    iosBundleId: 'com.example.spacewordSkorgameplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CtOe8mjabtzUnjxAfW6Vqp10CRE-qys',
    appId: '1:270601916854:web:74ca3ecb463a7584a37117',
    messagingSenderId: '270601916854',
    projectId: 'fir-211de',
    authDomain: 'fir-211de.firebaseapp.com',
    databaseURL: 'https://fir-211de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-211de.firebasestorage.app',
    measurementId: 'G-VGMW9EGV7F',
  );
}
